---
abstract: 'Perl extension for libconfig'
author:
  - 'cnangel <junliang.li@alibaba-inc.com>'
build_requires:
  ExtUtils::MakeMaker: 6.42
  Test::Base: 0.01
configure_requires:
  ExtUtils::MakeMaker: 6.42
distribution_type: module
generated_by: 'Module::Install version 0.82'
license: bsd
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Conf-Libconfig
no_index:
  directory:
    - inc
    - t
requires:
  Cwd: 1
  ExtUtils::XSBuilder: 0
  File::Find: 1
  XSLoader: 0.05
  perl: 5.6.1
resources:
  license: http://opensource.org/licenses/bsd-license.php
version: 0.02
