---
abstract: 'Perl extension for libconfig'
author:
  - 'Cnangel <cnangel@gmail.com>'
build_requires:
  ExtUtils::MakeMaker: 6.42
  ExtUtils::PkgConfig: 0
  Test::Deep: 0.1
  Test::Exception: 0.25
  Test::More: 0.60
  Test::Warn: 0.10
configure_requires:
  ExtUtils::MakeMaker: 6.30
  ExtUtils::PkgConfig: 0
distribution_type: module
generated_by: 'Module::Install version 1.00'
license: bsd
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Conf-Libconfig
no_index:
  directory:
    - inc
    - t
requires:
  XSLoader: 0.05
  perl: 5.6.1
resources:
  license: http://opensource.org/licenses/bsd-license.php
  repository: http://github.com/cnangel/Conf-Libconfig
version: 0.07
