---
abstract: 'Perl extension for libconfig'
author:
  - 'Cnangel <cnangel@gmail.com>'
build_requires:
  Test::Deep: 0.103
  Test::Exception: 0.27
  Test::NoTabs: 0.5
distribution_type: module
generated_by: 'Module::Install version 0.77'
license: bsd
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Conf-Libconfig
no_index:
  directory:
    - t
    - inc
    - inc
    - t
requires:
  Cwd: 1
  ExtUtils::XSBuilder: 0
  File::Find: 1
  XSLoader: 0.05
  perl: 5.6.1
version: 0.006
